In [1]:
from ddcrp_mdnd.network_model import *
from ddcrp_mdnd.my_util import *
from ddcrp_mdnd.helper import *
import networkx as nx

In [2]:
decay_fn = identity_decay()
distance = linear_distance
alpha = 1
gamma = 1
tau = 4
X_train = np.array([[0, 0, 1, 2, 3, 2], [4, 3, 0, 0, 1, 2]]).reshape((6,2))
X_train = np.array([[0,4],[0,3],[1,0],[2,0],[3,1],[2,2]])
init = np.array([2,0,1,3,5,3])
params = Params(alpha, gamma, tau, sample_params=False, Ztrain=X_train)
model = Model(X_train, distance, decay_fn, params, init=init)
print(model.prior)
# for edge in range(model.num_edges):
#     linked_edges = model.remove_link(edge, params)
#     model.sample_link_collapsed(edge, params, linked_edges)
#     print(model.cluster_of_edge.tolist())
#     model.sample_beta()

clusters: [0 0 0 1 1 1]
{0, 1}
Counter({0: 2, 1: 1})
Counter({4: 1, 3: 1, 0: 1})
Counter({2: 2, 3: 1})
Counter({0: 1, 1: 1, 2: 1})
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [3]:
model.sample_beta()
print(model.tables) # [4,2,3,2,1]
print(model.beta)

model.beta = np.array([0.4,0.2,0.1,0.1,0.1,0.1]) # for testing
print(model.beta)
print(model.beta.sum())

[4, 2, 3, 2, 1]
[0.17077638 0.26549216 0.20953717 0.13474671 0.21707675 0.00237084]
[0.4 0.2 0.1 0.1 0.1 0.1]
1.0


In [4]:
model.compute_llhood()
print(model.source_llhood) # [-3.5851, -6.2836]
print(model.sink_llhood) # [-6.1501, -5.4569]

Counter({0: 2, 1: 1})
Counter({4: 1, 3: 1, 0: 1})
Counter({2: 2, 3: 1})
Counter({0: 1, 1: 1, 2: 1})
[-3.58512022 -6.28360097  0.          0.          0.          0.        ]
[-6.15006958 -5.4569224   0.          0.          0.          0.        ]


In [5]:

# relink edge 4 to 2
linked_edges = model.remove_link(4, params) #{0:[0,1,2],1:[3,5],2:[4]}
print(list(nx.connected_components(model.graph)))
print(model.unique_clusters)
print(model.source_llhood) # [-3.5851,-3.5756, -2.3026]
print(model.sink_llhood) # [-6.1501, -3.4420, -1.6094] 
print(model.cluster_llhood)

Counter({2: 2})
Counter({0: 1, 2: 1})
Counter({3: 1})
Counter({1: 1})
[{0, 1, 2}, {3, 5}, {4}]
{0, 4, 5}
[-3.58512022 -6.28360097  0.          0.         -2.30258509 -3.57555077]
[-6.15006958 -5.4569224   0.          0.         -1.60943791 -3.44201938]
[ -9.7351898  -11.74052337   0.           0.          -3.91202301
  -7.01757014]


In [6]:
model.sample_link_collapsed(4, params, linked_edges, test_chosen=2)
print(list(nx.connected_components(model.graph)))
print(model.unique_clusters)
print(model.source_llhood) # [-6.4473, -3.5756]
print(model.sink_llhood) # [-8.3191, -3.4420] 
print(model.cluster_llhood)

Counter({0: 2, 1: 1, 3: 1})
Counter({4: 1, 3: 1, 0: 1, 1: 1})
Counter({2: 2, 3: 1})
Counter({0: 1, 2: 1, 1: 1})
[{0, 1, 2, 4}, {3, 5}]
{0, 5}
[-6.4473211  -6.28360097  0.          0.         -2.30258509 -3.57555077]
[-8.31912328 -5.4569224   0.          0.         -1.60943791 -3.44201938]
[-14.76644438 -11.74052337   0.           0.          -3.91202301
  -7.01757014]
