In [2]:
import numpy as np
from collections import Counter

In [109]:
alpha = 0.1
current_different_atoms = 0
count = Counter()
# x = np.array([1,5,5,5,5])
x = np.array([1,2,3,4,5])
np.random.shuffle(x)
print(x)
n = len(x)
lhood = 0
for i in range(n):
    if x[i] not in count:
        lhood += np.log(alpha) - np.log(alpha + i)
    else:
        lhood += np.log(count[x[i]]) - np.log(alpha + i)
    count[x[i]] += 1
lhood

[4 3 5 2 1]


-12.589976981711247

In [155]:
def sample_beta(msender, mreceiver, num_vertices, K, params):
    tables = np.zeros(num_vertices+1)
    num_tables = 0
    for cluster in range(K):
        for vertex in range(num_vertices):
            if msender[cluster][vertex]==1:
                tables[vertex]+=1
                num_tables+=1
            elif msender[cluster][vertex]>1:
                tmp= partitionCRP(params.alpha, msender[cluster][vertex])
                num_tables+=tmp
                tables[vertex]+=tmp
            if mreceiver[cluster][vertex]==1:
                tables[vertex]+=1
                num_tables+=1
            elif mreceiver[cluster][vertex]>1:
                tmp = partitionCRP(params.alpha, mreceiver[cluster][vertex])
                num_tables +=tmp
                tables[vertex]+=tmp

    tables[num_vertices] = params.gamma
    return tables, num_tables

#     tables[num_vertices] = params.gamma
#     beta = np.random.dirichlet(tables)
#     if any(beta==0):
#         raise Warning('something might be wrong')
#     return beta

def partitionCRP(alpha, N):
    K=0

    for iter in range(int(N)):
        r = np.random.rand()
        p = alpha/(alpha+iter)
        if r<p:
            K+=1

    return K

class Params():
    def __init__(self, alpha=0.5, gamma=0.5):
        self.alpha = alpha
        self.gamma = gamma
        
params = Params()
msender = np.array([[1,2],[2,3]])
mreceiver = np.array([[1,3],[2,4]])
print(sample_beta(msender, mreceiver, 2, 2, params))


(array([5. , 5. , 0.5]), 10)


In [182]:
a = set([1,2,3])
a += {1}
print(a)

TypeError: unsupported operand type(s) for +=: 'set' and 'set'

In [172]:
a = np.array([[1,2],[3,4]])
a = a[:,0]
b = np.array([3,4])
np.concatenate((a,b), axis=0)

array([1, 3, 3, 4])